### ISSUE TITLE
Creating Hawk with OrientDB backend from the Hawk Eclipse view throws exception

### ISSUE THREAD

**Issue by kolovos** [mondo-project/mondo-hawk#10]
The following exception is thrown:

```
java.lang.reflect.InvocationTargetException
	at org.hawk.ui2.wizard.HWizard$1.run(HWizard.java:84)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.core.runtime.CoreException: Plug-in "org.hawk.orientdb" was unable to instantiate class "org.hawk.orientdb.OrientDatabase".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:188)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.hawk.osgiserver.HManager.createGraph(HManager.java:132)
	at org.hawk.osgiserver.HModel.create(HModel.java:95)
	at org.hawk.ui2.wizard.HWizard.doFinish(HWizard.java:118)
	at org.hawk.ui2.wizard.HWizard.access$0(HWizard.java:113)
	at org.hawk.ui2.wizard.HWizard$1.run(HWizard.java:80)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/db/ODatabaseDocumentInternal
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getConstructor0(Class.java:2964)
	at java.lang.Class.newInstance(Class.java:403)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.orient.core.db.ODatabaseDocumentInternal cannot be found by org.hawk.orientdb_1.0.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:336)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:328)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

```

**Comment by bluezio** [comment]
I've just tried running it from source and it works fine. I think it might be something in how we build the update site.

**Comment by bluezio** [comment]
Tried installing the 1.0.0.201510301407 update site and it's worked fine from a clean Eclipse Mars installation. I've also checked the org.hawk.orientdb.*.jar within plugins/ and it did have the OrientDB libraries in it. Could you try updating and creat the instance again?

**Comment by bluezio** [comment]
Oh, and if you're running from source, you'll need to fetch the OrientDB libraries using [IvyDE][https://ant.apache.org/ivy/ivyde/download.html]. Right click on the project and click "Ivy > Retrieve".

**Comment by kolovos** [comment]
It does work fine indeed. My bad.
